spring.application.name=food-delivery-platform



spring.datasource.url=jdbc:mysql://localhost:3306/food_delivery1
spring.datasource.username=root
spring.datasource.password=Atr50$6eW77
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.main.web-application-type=servlet
server.port=8080

